/* tslint:disable */
/* eslint-disable */
/**
 * HiveSync API 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForgotPasswordModel
 */
export interface ForgotPasswordModel {
    /**
     * 
     * @type {string}
     * @memberof ForgotPasswordModel
     */
    email?: string;
}

/**
 * Check if a given object implements the ForgotPasswordModel interface.
 */
export function instanceOfForgotPasswordModel(value: object): value is ForgotPasswordModel {
    return true;
}

export function ForgotPasswordModelFromJSON(json: any): ForgotPasswordModel {
    return ForgotPasswordModelFromJSONTyped(json, false);
}

export function ForgotPasswordModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForgotPasswordModel {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function ForgotPasswordModelToJSON(json: any): ForgotPasswordModel {
    return ForgotPasswordModelToJSONTyped(json, false);
}

export function ForgotPasswordModelToJSONTyped(value?: ForgotPasswordModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

