/* tslint:disable */
/* eslint-disable */
/**
 * HiveSync API 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectDetailDto
 */
export interface ProjectDetailDto {
    /**
     * 
     * @type {string}
     * @memberof ProjectDetailDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDetailDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDetailDto
     */
    color: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectDetailDto
     */
    isDefault: boolean;
}

/**
 * Check if a given object implements the ProjectDetailDto interface.
 */
export function instanceOfProjectDetailDto(value: object): value is ProjectDetailDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('color' in value) || value['color'] === undefined) return false;
    if (!('isDefault' in value) || value['isDefault'] === undefined) return false;
    return true;
}

export function ProjectDetailDtoFromJSON(json: any): ProjectDetailDto {
    return ProjectDetailDtoFromJSONTyped(json, false);
}

export function ProjectDetailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDetailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'color': json['color'],
        'isDefault': json['isDefault'],
    };
}

export function ProjectDetailDtoToJSON(json: any): ProjectDetailDto {
    return ProjectDetailDtoToJSONTyped(json, false);
}

export function ProjectDetailDtoToJSONTyped(value?: ProjectDetailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'color': value['color'],
        'isDefault': value['isDefault'],
    };
}

