/* tslint:disable */
/* eslint-disable */
/**
 * HiveSync API 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResendConfirmationEmailModel
 */
export interface ResendConfirmationEmailModel {
    /**
     * 
     * @type {string}
     * @memberof ResendConfirmationEmailModel
     */
    email: string;
}

/**
 * Check if a given object implements the ResendConfirmationEmailModel interface.
 */
export function instanceOfResendConfirmationEmailModel(value: object): value is ResendConfirmationEmailModel {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function ResendConfirmationEmailModelFromJSON(json: any): ResendConfirmationEmailModel {
    return ResendConfirmationEmailModelFromJSONTyped(json, false);
}

export function ResendConfirmationEmailModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResendConfirmationEmailModel {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function ResendConfirmationEmailModelToJSON(json: any): ResendConfirmationEmailModel {
    return ResendConfirmationEmailModelToJSONTyped(json, false);
}

export function ResendConfirmationEmailModelToJSONTyped(value?: ResendConfirmationEmailModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

