/* tslint:disable */
/* eslint-disable */
/**
 * HiveSync API 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetPasswordModel
 */
export interface ResetPasswordModel {
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordModel
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordModel
     */
    token?: string;
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordModel
     */
    newPassword?: string;
}

/**
 * Check if a given object implements the ResetPasswordModel interface.
 */
export function instanceOfResetPasswordModel(value: object): value is ResetPasswordModel {
    return true;
}

export function ResetPasswordModelFromJSON(json: any): ResetPasswordModel {
    return ResetPasswordModelFromJSONTyped(json, false);
}

export function ResetPasswordModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetPasswordModel {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'token': json['token'] == null ? undefined : json['token'],
        'newPassword': json['newPassword'] == null ? undefined : json['newPassword'],
    };
}

export function ResetPasswordModelToJSON(json: any): ResetPasswordModel {
    return ResetPasswordModelToJSONTyped(json, false);
}

export function ResetPasswordModelToJSONTyped(value?: ResetPasswordModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'token': value['token'],
        'newPassword': value['newPassword'],
    };
}

