/* tslint:disable */
/* eslint-disable */
/**
 * HiveSync API 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectDetailDto } from './ProjectDetailDto';
import {
    ProjectDetailDtoFromJSON,
    ProjectDetailDtoFromJSONTyped,
    ProjectDetailDtoToJSON,
    ProjectDetailDtoToJSONTyped,
} from './ProjectDetailDto';

/**
 * 
 * @export
 * @interface SectionDetailDto
 */
export interface SectionDetailDto {
    /**
     * 
     * @type {string}
     * @memberof SectionDetailDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SectionDetailDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SectionDetailDto
     */
    color: string;
    /**
     * 
     * @type {ProjectDetailDto}
     * @memberof SectionDetailDto
     */
    project: ProjectDetailDto;
}

/**
 * Check if a given object implements the SectionDetailDto interface.
 */
export function instanceOfSectionDetailDto(value: object): value is SectionDetailDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('color' in value) || value['color'] === undefined) return false;
    if (!('project' in value) || value['project'] === undefined) return false;
    return true;
}

export function SectionDetailDtoFromJSON(json: any): SectionDetailDto {
    return SectionDetailDtoFromJSONTyped(json, false);
}

export function SectionDetailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SectionDetailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'color': json['color'],
        'project': ProjectDetailDtoFromJSON(json['project']),
    };
}

export function SectionDetailDtoToJSON(json: any): SectionDetailDto {
    return SectionDetailDtoToJSONTyped(json, false);
}

export function SectionDetailDtoToJSONTyped(value?: SectionDetailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'color': value['color'],
        'project': ProjectDetailDtoToJSON(value['project']),
    };
}

