/* tslint:disable */
/* eslint-disable */
/**
 * HiveSync API 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SectionDetailDto } from './SectionDetailDto';
import {
    SectionDetailDtoFromJSON,
    SectionDetailDtoFromJSONTyped,
    SectionDetailDtoToJSON,
    SectionDetailDtoToJSONTyped,
} from './SectionDetailDto';
import type { TodoPriority } from './TodoPriority';
import {
    TodoPriorityFromJSON,
    TodoPriorityFromJSONTyped,
    TodoPriorityToJSON,
    TodoPriorityToJSONTyped,
} from './TodoPriority';
import type { TodoState } from './TodoState';
import {
    TodoStateFromJSON,
    TodoStateFromJSONTyped,
    TodoStateToJSON,
    TodoStateToJSONTyped,
} from './TodoState';
import type { ProjectDetailDto } from './ProjectDetailDto';
import {
    ProjectDetailDtoFromJSON,
    ProjectDetailDtoFromJSONTyped,
    ProjectDetailDtoToJSON,
    ProjectDetailDtoToJSONTyped,
} from './ProjectDetailDto';

/**
 * 
 * @export
 * @interface TodoDetailDto
 */
export interface TodoDetailDto {
    /**
     * 
     * @type {string}
     * @memberof TodoDetailDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TodoDetailDto
     */
    summary: string;
    /**
     * 
     * @type {string}
     * @memberof TodoDetailDto
     */
    description?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TodoDetailDto
     */
    dueAt?: Date | null;
    /**
     * 
     * @type {TodoPriority}
     * @memberof TodoDetailDto
     */
    priority: TodoPriority;
    /**
     * 
     * @type {TodoState}
     * @memberof TodoDetailDto
     */
    state: TodoState;
    /**
     * 
     * @type {ProjectDetailDto}
     * @memberof TodoDetailDto
     */
    project: ProjectDetailDto;
    /**
     * 
     * @type {SectionDetailDto}
     * @memberof TodoDetailDto
     */
    section?: SectionDetailDto;
}



/**
 * Check if a given object implements the TodoDetailDto interface.
 */
export function instanceOfTodoDetailDto(value: object): value is TodoDetailDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('project' in value) || value['project'] === undefined) return false;
    return true;
}

export function TodoDetailDtoFromJSON(json: any): TodoDetailDto {
    return TodoDetailDtoFromJSONTyped(json, false);
}

export function TodoDetailDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoDetailDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'summary': json['summary'],
        'description': json['description'] == null ? undefined : json['description'],
        'dueAt': json['dueAt'] == null ? undefined : (new Date(json['dueAt'])),
        'priority': TodoPriorityFromJSON(json['priority']),
        'state': TodoStateFromJSON(json['state']),
        'project': ProjectDetailDtoFromJSON(json['project']),
        'section': json['section'] == null ? undefined : SectionDetailDtoFromJSON(json['section']),
    };
}

export function TodoDetailDtoToJSON(json: any): TodoDetailDto {
    return TodoDetailDtoToJSONTyped(json, false);
}

export function TodoDetailDtoToJSONTyped(value?: TodoDetailDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'summary': value['summary'],
        'description': value['description'],
        'dueAt': value['dueAt'] == null ? value['dueAt'] : value['dueAt'].toISOString(),
        'priority': TodoPriorityToJSON(value['priority']),
        'state': TodoStateToJSON(value['state']),
        'project': ProjectDetailDtoToJSON(value['project']),
        'section': SectionDetailDtoToJSON(value['section']),
    };
}

