/* tslint:disable */
/* eslint-disable */
/**
 * HiveSync API 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TodoPriority } from './TodoPriority';
import {
    TodoPriorityFromJSON,
    TodoPriorityFromJSONTyped,
    TodoPriorityToJSON,
    TodoPriorityToJSONTyped,
} from './TodoPriority';
import type { TodoState } from './TodoState';
import {
    TodoStateFromJSON,
    TodoStateFromJSONTyped,
    TodoStateToJSON,
    TodoStateToJSONTyped,
} from './TodoState';

/**
 * 
 * @export
 * @interface UpdateTodoDto
 */
export interface UpdateTodoDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateTodoDto
     */
    summary?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateTodoDto
     */
    description?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UpdateTodoDto
     */
    dueAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateTodoDto
     */
    projectId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateTodoDto
     */
    sectionId?: string | null;
    /**
     * 
     * @type {TodoPriority}
     * @memberof UpdateTodoDto
     */
    priorityId?: TodoPriority;
    /**
     * 
     * @type {TodoState}
     * @memberof UpdateTodoDto
     */
    stateId?: TodoState;
}



/**
 * Check if a given object implements the UpdateTodoDto interface.
 */
export function instanceOfUpdateTodoDto(value: object): value is UpdateTodoDto {
    return true;
}

export function UpdateTodoDtoFromJSON(json: any): UpdateTodoDto {
    return UpdateTodoDtoFromJSONTyped(json, false);
}

export function UpdateTodoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTodoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'summary': json['summary'] == null ? undefined : json['summary'],
        'description': json['description'] == null ? undefined : json['description'],
        'dueAt': json['dueAt'] == null ? undefined : (new Date(json['dueAt'])),
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'sectionId': json['sectionId'] == null ? undefined : json['sectionId'],
        'priorityId': json['priorityId'] == null ? undefined : TodoPriorityFromJSON(json['priorityId']),
        'stateId': json['stateId'] == null ? undefined : TodoStateFromJSON(json['stateId']),
    };
}

export function UpdateTodoDtoToJSON(json: any): UpdateTodoDto {
    return UpdateTodoDtoToJSONTyped(json, false);
}

export function UpdateTodoDtoToJSONTyped(value?: UpdateTodoDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'summary': value['summary'],
        'description': value['description'],
        'dueAt': value['dueAt'] == null ? value['dueAt'] : value['dueAt'].toISOString(),
        'projectId': value['projectId'],
        'sectionId': value['sectionId'],
        'priorityId': TodoPriorityToJSON(value['priorityId']),
        'stateId': TodoStateToJSON(value['stateId']),
    };
}

