/* tslint:disable */
/* eslint-disable */
/**
 * HiveSync API 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddProjectDto,
  ProblemDetails,
  ProjectDetailDto,
  UpdateProjectDto,
} from '../models/index';
import {
    AddProjectDtoFromJSON,
    AddProjectDtoToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    ProjectDetailDtoFromJSON,
    ProjectDetailDtoToJSON,
    UpdateProjectDtoFromJSON,
    UpdateProjectDtoToJSON,
} from '../models/index';

export interface ApiProjectIdDeleteRequest {
    id: string;
}

export interface ApiProjectIdGetRequest {
    id: string;
}

export interface ApiProjectIdPatchRequest {
    id: string;
    updateProjectDto?: UpdateProjectDto;
}

export interface ApiProjectPostRequest {
    addProjectDto?: AddProjectDto;
}

/**
 * 
 */
export class ProjectApi extends runtime.BaseAPI {

    /**
     */
    async apiProjectGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProjectDetailDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Project`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProjectDetailDtoFromJSON));
    }

    /**
     */
    async apiProjectGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProjectDetailDto>> {
        const response = await this.apiProjectGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiProjectIdDeleteRaw(requestParameters: ApiProjectIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiProjectIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Project/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiProjectIdDelete(requestParameters: ApiProjectIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiProjectIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiProjectIdGetRaw(requestParameters: ApiProjectIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectDetailDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiProjectIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Project/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectDetailDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiProjectIdGet(requestParameters: ApiProjectIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectDetailDto> {
        const response = await this.apiProjectIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiProjectIdPatchRaw(requestParameters: ApiProjectIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectDetailDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiProjectIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Project/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateProjectDtoToJSON(requestParameters['updateProjectDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectDetailDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiProjectIdPatch(requestParameters: ApiProjectIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectDetailDto> {
        const response = await this.apiProjectIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiProjectPostRaw(requestParameters: ApiProjectPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectDetailDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Project`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddProjectDtoToJSON(requestParameters['addProjectDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectDetailDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiProjectPost(requestParameters: ApiProjectPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectDetailDto> {
        const response = await this.apiProjectPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
