/* tslint:disable */
/* eslint-disable */
/**
 * HiveSync API 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddSectionDto,
  ProblemDetails,
  SectionDetailDto,
  UpdateSectionDto,
} from '../models/index';
import {
    AddSectionDtoFromJSON,
    AddSectionDtoToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    SectionDetailDtoFromJSON,
    SectionDetailDtoToJSON,
    UpdateSectionDtoFromJSON,
    UpdateSectionDtoToJSON,
} from '../models/index';

export interface ApiSectionIdDeleteRequest {
    id: string;
}

export interface ApiSectionIdGetRequest {
    id: string;
}

export interface ApiSectionIdPatchRequest {
    id: string;
    updateSectionDto?: UpdateSectionDto;
}

export interface ApiSectionPostRequest {
    addSectionDto?: AddSectionDto;
}

export interface ApiSectionProjectProjectIdGetRequest {
    projectId: string;
}

/**
 * 
 */
export class SectionApi extends runtime.BaseAPI {

    /**
     */
    async apiSectionGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SectionDetailDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Section`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SectionDetailDtoFromJSON));
    }

    /**
     */
    async apiSectionGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SectionDetailDto>> {
        const response = await this.apiSectionGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiSectionIdDeleteRaw(requestParameters: ApiSectionIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiSectionIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Section/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiSectionIdDelete(requestParameters: ApiSectionIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiSectionIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiSectionIdGetRaw(requestParameters: ApiSectionIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SectionDetailDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiSectionIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Section/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SectionDetailDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiSectionIdGet(requestParameters: ApiSectionIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SectionDetailDto> {
        const response = await this.apiSectionIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiSectionIdPatchRaw(requestParameters: ApiSectionIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SectionDetailDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiSectionIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Section/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateSectionDtoToJSON(requestParameters['updateSectionDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SectionDetailDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiSectionIdPatch(requestParameters: ApiSectionIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SectionDetailDto> {
        const response = await this.apiSectionIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiSectionPostRaw(requestParameters: ApiSectionPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SectionDetailDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Section`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddSectionDtoToJSON(requestParameters['addSectionDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SectionDetailDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiSectionPost(requestParameters: ApiSectionPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SectionDetailDto> {
        const response = await this.apiSectionPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiSectionProjectProjectIdGetRaw(requestParameters: ApiSectionProjectProjectIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SectionDetailDto>>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling apiSectionProjectProjectIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Section/project/{projectId}`;
        urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SectionDetailDtoFromJSON));
    }

    /**
     */
    async apiSectionProjectProjectIdGet(requestParameters: ApiSectionProjectProjectIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SectionDetailDto>> {
        const response = await this.apiSectionProjectProjectIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
