/* tslint:disable */
/* eslint-disable */
/**
 * HiveSync API 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddTodoDto,
  ProblemDetails,
  TodoDetailDto,
  UpdateTodoDto,
} from '../models/index';
import {
    AddTodoDtoFromJSON,
    AddTodoDtoToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    TodoDetailDtoFromJSON,
    TodoDetailDtoToJSON,
    UpdateTodoDtoFromJSON,
    UpdateTodoDtoToJSON,
} from '../models/index';

export interface ApiTodoIdDeleteRequest {
    id: string;
}

export interface ApiTodoIdGetRequest {
    id: string;
}

export interface ApiTodoIdPatchRequest {
    id: string;
    updateTodoDto?: UpdateTodoDto;
}

export interface ApiTodoPostRequest {
    addTodoDto?: AddTodoDto;
}

export interface ApiTodoProjectProjectIdGetRequest {
    projectId: string;
}

export interface ApiTodoSectionSectionIdGetRequest {
    sectionId: string;
}

/**
 * 
 */
export class TodoApi extends runtime.BaseAPI {

    /**
     */
    async apiTodoGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TodoDetailDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Todo`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TodoDetailDtoFromJSON));
    }

    /**
     */
    async apiTodoGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TodoDetailDto>> {
        const response = await this.apiTodoGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiTodoIdDeleteRaw(requestParameters: ApiTodoIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiTodoIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Todo/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiTodoIdDelete(requestParameters: ApiTodoIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiTodoIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiTodoIdGetRaw(requestParameters: ApiTodoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TodoDetailDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiTodoIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Todo/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TodoDetailDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiTodoIdGet(requestParameters: ApiTodoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TodoDetailDto> {
        const response = await this.apiTodoIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiTodoIdPatchRaw(requestParameters: ApiTodoIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TodoDetailDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiTodoIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Todo/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTodoDtoToJSON(requestParameters['updateTodoDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TodoDetailDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiTodoIdPatch(requestParameters: ApiTodoIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TodoDetailDto> {
        const response = await this.apiTodoIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiTodoPostRaw(requestParameters: ApiTodoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TodoDetailDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Todo`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddTodoDtoToJSON(requestParameters['addTodoDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TodoDetailDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiTodoPost(requestParameters: ApiTodoPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TodoDetailDto> {
        const response = await this.apiTodoPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiTodoProjectProjectIdGetRaw(requestParameters: ApiTodoProjectProjectIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TodoDetailDto>>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling apiTodoProjectProjectIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Todo/project/{projectId}`;
        urlPath = urlPath.replace(`{${"projectId"}}`, encodeURIComponent(String(requestParameters['projectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TodoDetailDtoFromJSON));
    }

    /**
     */
    async apiTodoProjectProjectIdGet(requestParameters: ApiTodoProjectProjectIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TodoDetailDto>> {
        const response = await this.apiTodoProjectProjectIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiTodoSectionSectionIdGetRaw(requestParameters: ApiTodoSectionSectionIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TodoDetailDto>>> {
        if (requestParameters['sectionId'] == null) {
            throw new runtime.RequiredError(
                'sectionId',
                'Required parameter "sectionId" was null or undefined when calling apiTodoSectionSectionIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Todo/section/{sectionId}`;
        urlPath = urlPath.replace(`{${"sectionId"}}`, encodeURIComponent(String(requestParameters['sectionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TodoDetailDtoFromJSON));
    }

    /**
     */
    async apiTodoSectionSectionIdGet(requestParameters: ApiTodoSectionSectionIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TodoDetailDto>> {
        const response = await this.apiTodoSectionSectionIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
